import type { Skill } from "../domain";

export const skillsData: Skill[] = [
  {
    id: "react",
    name: "React",
    icon: "/images/react.min.webp",
    level: 5,
    mastery: 92,
    category: "frontend",
    color: "cyan",
    description: "Component architecture, hooks, RSC & App Router",
  },
  {
    id: "typescript",
    name: "TypeScript",
    icon: "/images/typescript.min.webp",
    level: 5,
    mastery: 90,
    category: "frontend",
    color: "cyan",
    description: "Strict typing, generics, utility types & advanced patterns",
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "/images/nextjs.min.webp",
    level: 5,
    mastery: 85,
    category: "frontend",
    color: "fuchsia",
    description: "App Router, RSC, Server Actions & edge rendering",
  },
  {
    id: "nest",
    name: "NestJS",
    icon: "/images/nestjs.min.webp",
    level: 4,
    mastery: 70,
    category: "backend",
    color: "fuchsia",
    description: "REST APIs, streaming, event loop & performance tuning",
  },
  // {
  //   id: "nodejs",
  //   name: "Node.js",
  //   icon: "🟩",
  //   level: 4,
  //   mastery: 82,
  //   category: "backend",
  //   color: "green",
  //   description: "REST APIs, streaming, event loop & performance tuning",
  // },
  {
    id: "docker",
    name: "Docker",
    icon: "/images/docker.min.webp",
    level: 3,
    mastery: 72,
    category: "devops",
    color: "cyan",
    description: "Containers, compose, multi-stage builds & dev workflows",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    icon: "/images/postgress.min.webp",
    level: 4,
    mastery: 70,
    category: "backend",
    color: "cyan",
    description: "Complex queries, indexes, transactions & optimization",
  },
  {
    id: "git",
    name: "Git / CI",
    icon: "/images/github.min.webp",
    level: 4,
    mastery: 90,
    category: "tools",
    color: "green",
    description: "Git flow, GitHub Actions, CI/CD pipelines",
  },
  {
    id: "php",
    name: "PHP",
    icon: "/images/php.min.webp",
    level: 4,
    mastery: 70,
    category: "backend",
    color: "fuchsia",
    description: "REST APIs, streaming, event loop & performance tuning",
  },
  {
    id: "expo",
    name: "Expo",
    icon: "/images/expo.min.webp",
    level: 4,
    mastery: 65,
    category: "frontend",
    color: "green",
    description: "REST APIs, streaming, event loop & performance tuning",
  },
  {
    id: "flutter",
    name: "Flutter",
    icon: "/images/flutter.min.webp",
    level: 4,
    mastery: 65,
    category: "frontend",
    color: "green",
    description: "REST APIs, streaming, event loop & performance tuning",
  },
  {
    id: "dart",
    name: "Dart",
    icon: "/images/dart.min.webp",
    level: 4,
    mastery: 65,
    category: "frontend",
    color: "green",
    description: "REST APIs, streaming, event loop & performance tuning",
  }
];
